remote_theme: "mmistakes/minimal-mistakes@4.16.4"

title: Distributed Text Services Specifications
description: The Distributed Text Services (DTS) Specification defines a Hypermedia-Driven Web API for working with collections of text as machine-actionable data.
show_downloads: false
search: true
menu:
  - title : "Entry Point"
    url: "Entry.html"
  - title : "Collections Endpoint"
    url: "Collections-Endpoint.html"
  - title : "Navigation Endpoint"
    url: "Navigation-Endpoint.html"
  - title : "Documents Endpoint"
    url: "Documents-Endpoint.html"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache