theme: jekyll-theme-leap-day
title: Distributed Text Services Specifications
description: The Distributed Text Services (DTS) Specification defines a Hypermedia-Driven Web API for working with collections of text as machine-actionable data.
show_downloads: false
menu:
  - title : "Entry Point"
    url: "Entry.html"
  - title : "Collection Endpoint"
    url: "Collection-Endpoint.html"
  - title : "Navigation Endpoint"
    url: "Navigation-Endpoint.html"
  - title : "Document Endpoint"
    url: "Document-Endpoint.html"